name: compound_risk

channels:
  - conda-forge

# note that these are the developer dependencies,
# if you only want the user dependencies, see
# install_requires in setup.py
dependencies:
  - affine
  - click
  - bottleneck
  - cartopy 
  - cycler
  - dask
  - descartes 
  - entrypoints
  - flit>=3.2
  - fonttools
  - gdal==3.4.1
  - geopandas==0.10.2
  - hydromt==0.5.0
  - hydromt_sfincs==0.2.2
  - jupyter
  - kiwisolver
  - netcdf4
  - matplotlib 
  - numba
  - numpy
  - openpyxl
  - packaging
  - pandas
  - pillow
  - pip
  - pyflwdir==0.5.5
  - pygeos>=0.8
  - pyproj==3.4.1
  - python==3.9
  - python-dateutil
  - rasterio==1.3.4
  - requests
  - rioxarray==0.11.1
  - scipy
  - toml
  - xarray==2022.3.0
  - zarr
  - pip:
    - matplotlib_scalebar
    - pyvinecopulib